### ISSUE TITLE
Paper information wishlist for programme (paper-id, paper title, authors, abstract) - not urgent 

### ISSUE THREAD

**Issue by MinaAlmasi** [cohure/CHR2024-website#28]
# Paper Information Wishlist (not urgent!!)
With the new programme (#27), the suggestion is to add each paper as a separate page (kind of like the discourse forums did last year). See mock pictures (that will be tweaked to make it prettier). For this, I would ideally need an excel file with 

1. `Paper-id`
2. `Paper title `
3. `Authors`
4. `Abstract`

If possible, would also be nice to have a column called "`session_number`", but I can add this manually if it is too much of an hassle! If any of the information above is difficult to get in an excel file, I will find a way around it - just let me know @awlassche!

This is not urgent, I know the proceedings take time! 

### Mock pictures (*not* released, also presented in #27)
Each paper will be placed in underneath their respective session as their title that is hyperlinked. The hyperlinked page will lead to a new page with title, link to paper, authors, abstract etc. See pictures below for this - I will tweak them to make them prettier for the website. 

#### Mock Sessions Overview
<img width="80%" alt="sessions-mock" src="https://github.com/user-attachments/assets/e1eb5bb6-3447-4b48-9e69-5174c4538be7">

#### Mock paper page 
<img width="80%" alt="paper-mock" src="https://github.com/user-attachments/assets/9d1213fb-650d-41c9-b196-a60333464d78">

**Comment by marijnkoolen** [comment]
@MinaAlmasi: Apologies that this took so long, but we finally have the programme ready. I can add a CSV/Excel file with `paper-id`, `title`, `author`, `type` (short/long), `session-id`, `session-name`. I don't think getting the abstracts out of the PDF or LaTeX source files is going to be easy, but I can have a go at that as well. 

I'll push the file to the repository probably later today.

**Comment by awlassche** [comment]
I have already given @MinaAlmasi a json file with `paper-id`, `title`, `author`, and `abstract`, created by Folgert. If the paper-ids are the same, they are easy to merge! Otherwise title would also work.

**Comment by MinaAlmasi** [comment]
> @MinaAlmasi: Apologies that this took so long, but we finally have the programme ready. I can add a CSV/Excel file with `paper-id`, `title`, `author`, `type` (short/long), `session-id`, `session-name`. I don't think getting the abstracts out of the PDF or LaTeX source files is going to be easy, but I can have a go at that as well.
> 
> I'll push the file to the repository probably later today.

Hi @marijnkoolen ! Thank you for your response!

As Allie writes, I have already gotten the file with abstracts from Folgert that I'm using to automate web-pages for the papers on the newly created [cohure/website-automatisation](https://github.com/cohure/website-automatisation)

But that file (called [abstracts.json](https://github.com/cohure/website-automatisation/blob/main/in/abstracts.json)) does not have the session-id and session-name. So I would actually love a CSV/Excel file with  `paper-id`, `session-id` and `session-name` so that I can combine that with the abstracts file. 

If you are able to, you are welcome to push that CSV/Excel file to [cohure/website-automatisation](https://github.com/cohure/website-automatisation) instead of this repository, as I'm in the process of cleaning this repo to only include html/md for the website. If this is an extra hassle, then just push the file to this repository (or alternatively mail me at mina@cas.au.dk)!

Thank you again, and don't hesitate to contact me if there is anything I can do!

**Comment by MinaAlmasi** [comment]
Hi @marijnkoolen ! 

I should have sent you an invite as collaborator to the repository!

**Comment by marijnkoolen** [comment]
Great, I've pushed a TSV file with the session info.

**Comment by marijnkoolen** [comment]
Hi @MinaAlmasi, I'd like to put the programme online today so participants know when their presentation is going to be. I just want to check that we're not both doing the same thing. Are you making pages per paper? Or are you also filling in the programme details? No worries if you're not, I'm happy to do it. I just don't want our efforts to clash.

**Comment by MinaAlmasi** [comment]
Hi @marijnkoolen 

I'll be making both the programme and pages per paper, and I'm aiming at getting it up today!

So you don't need to do anything - except for maybe checking that everything looks nice when it is up, and letting me know if there is anything I can make better/more clear. 

Thanks for the offer though!

**Comment by marijnkoolen** [comment]
Great, thanks! Once the proceedings are published on CEUR-WS, we can replace the dummy link in the TSV I made with the proper link to the paper PDFs and update the paper pages.

**Comment by MinaAlmasi** [comment]
Awesome! Yes I can replace the "Vol-dummy" with the actual "vol" whenever it is ready!

**Comment by MinaAlmasi** [comment]
Closing this now, if you notice anything weird on the website, you can also write in #43
