### ISSUE TITLE
Wishlist thread: Any wishes for improvements / changes to the website?

### ISSUE THREAD

**Issue by MinaAlmasi** [cohure/CHR2024-website#43]
Hi all. Thanks for inputs, files and help!

I'm opening this issue, so that you can write me in this thread, if there are any things you notice on the website that are weird (to keep it one place!). I strive to make changes regularly, but if it is not urgent, it might not be immediate! 

Looking forward to CHR! 

@awlassche @marijnkoolen

**Comment by awlassche** [comment]
can we add the names of the keynote speakers (Leon and Lauren) in the program?

**Comment by MinaAlmasi** [comment]
> can we add the names of the keynote speakers (Leon and Lauren) in the program?

Yes thank you! I'll add a link to the announcement about them !

**Comment by marijnkoolen** [comment]
I made a mistake when adding the posters to the `session_papers.tsv`. There two papers mentioned in `abstracts.json` that are published in the proceedings but not presented at the conference (short paper with number 38 and long paper with number 140) because they are authored by people working at Russian institutions, who are not allowed to participate, following the Aarhus University policy in place at the moment (but their papers were reviewed and accepted by the time we figured this out). 

Both are now listed in the poster session, but they won't be presented as posters. Is it possible to only list them in the accepted papers, and not in the poster session? Sorry for the hassle and for not getting this right straight away.

**Comment by MinaAlmasi** [comment]
> (short paper with number 38 and long paper with number 140

Hi again @marijnkoolen ! I have just quickly removed them manually and will include this in the automation script later - no worries! It should be up now? 

I'll be offline from now and until 9:00 (CET) tomorrow, but you can catch me all day tomorrow, if you notice anything else weird!

**Comment by melvinwevers** [comment]
It might be nice to see whether something is a short or long paper in the overviews. Now you have to click on the paper to see whether it is a short or long paper. Perhaps a icon or just LP or SP would be nice. If this involves a lot of manual labor than please ignore this request.

**Comment by melvinwevers** [comment]
The lightning talk sessions link now does not do anything. Maybe a short text explaining what this section is might be nice. @marijnkoolen @MinaAlmasi

**Comment by MinaAlmasi** [comment]
> It might be nice to see whether something is a short or long paper in the overviews. Now you have to click on the paper to see whether it is a short or long paper. Perhaps a icon or just LP or SP would be nice. If this involves a lot of manual labor than please ignore this request.

I will make a note of this. The reason for not including it was that I did not want to clutter the overview too much, but if this information is important, I'll see whether I can add a (short)/(long) connected to each paper somehow.

**Comment by MinaAlmasi** [comment]
> The lightning talk sessions link now does not do anything. Maybe a short text explaining what this section is might be nice. @marijnkoolen @MinaAlmasi

Not sure where to add lightning talks given that we also have a lot of information of sessions and posters in the programme overview for Thursday. I can make a separate page that lightning talks links to? Open to any suggestions @melvinwevers 

I also am missing a list or file of the lightning talks!

**Comment by marijnkoolen** [comment]
Many thanks. I realised I made another mistake with the info in `session_papers.tsv`. I mixed up paper type (LONG/SHORT) and format (oral, poster, or "n/a"). 

I think the programme is correct now, but the list of accepted papers now lists both 38 and 140 as poster papers, while neither is presented as poster and 140 is a long paper. Can you change that list to only mention whether a paper is a long or short paper, and remove all the information about sessions (including the poster session). That way, the list correctly shows all accepted papers and all their correct types. 

I'll make a list of the lightning talks and add it to the `session_papers.tsv`.

**Comment by MinaAlmasi** [comment]
> Many thanks. I realised I made another mistake with the info in `session_papers.tsv`. I mixed up paper type (LONG/SHORT) and format (oral, poster, or "n/a").
> 
> I think the programme is correct now, but the list of accepted papers now lists both 38 and 140 as poster papers, while neither is presented as poster and 140 is a long paper. Can you change that list to only mention whether a paper is a long or short paper, and remove all the information about sessions (including the poster session). That way, the list correctly shows all accepted papers and all their correct types.
> 
> I'll make a list of the lightning talks and add it to the `session_papers.tsv`.

Just to make sure I get this. I have to make an accepted papers page without any mention of sessions etc. 

The session for poster papers will in the file be updated to say "poster" and the type will exclusively be about 
1. Make accepted papers a page without any mention of sessions
2. Session for poster papers will be updated to say "poster" and the type will exclusively be LONG/SHORT ?

**Comment by marijnkoolen** [comment]
Sorry, the lightning talks aren't in there yet. There is a column `format` that says either 'oral', 'poster' or 'n/a' (for the two non-presented papers) and I'll add 'lightning' for the lightning talks. In the column `type` there is only 'long' and 'short' and I'll 'lightning' there as well.

**Comment by MinaAlmasi** [comment]
> Sorry, the lightning talks aren't in there yet. There is a column `format` that says either 'oral', 'poster' or 'n/a' (for the two non-presented papers) and I'll add 'lightning' for the lightning talks. In the column `type` there is only 'long' and 'short' and I'll 'lightning' there as well.

Perfekt. Thank you for the help!

**Comment by marijnkoolen** [comment]
Okay, I've uploaded a new version with all the lightning talks. They have no up-to-date abstracts nor easy to obtain abstracts, and they are not published in the proceedings, so I think they shouldn't get their own page.

**Comment by awlassche** [comment]
> I will make a note of this. The reason for not including it was that I did not want to clutter the overview too much, but if this information is important, I'll see whether I can add a (short)/(long) connected to each paper somehow.

It is helpful so people can calculate what time which talk starts (in case they for example have to enter half way a session). Maybe it can be added in brackets after the title (not included in the link)? Just a 'short' or 'SP' and 'long' or 'LP'?

**Comment by awlassche** [comment]
> Okay, I've uploaded a new version with all the lightning talks. They have no up-to-date abstracts nor easy to obtain abstracts, and they are not published in the proceedings, so I think they shouldn't get their own page.

Agreed, I think adding the titles and authors of the lightning talk at the bottom of the 'Thursday' page is fine. They do not have to link to separate pages.

**Comment by MinaAlmasi** [comment]
> > I will make a note of this. The reason for not including it was that I did not want to clutter the overview too much, but if this information is important, I'll see whether I can add a (short)/(long) connected to each paper somehow.
> 
> It is helpful so people can calculate what time which talk starts (in case they for example have to enter half way a session). Maybe it can be added in brackets after the title (not included in the link)? Just a 'short' or 'SP' and 'long' or 'LP'?
> 
> Not very urgent tho!

Thanks both @awlassche and @melvinwevers for pointing it out! I'll fix at some point - I have some other CHC stuff today also. But I'm thinking something like this (in both "Accepted Papers" and "Programme"): 
<img width="996" alt="short:long brackets" src="https://github.com/user-attachments/assets/9b0cb17b-a697-4d71-9fe2-2bee9358cc10">

**Comment by MinaAlmasi** [comment]
> Okay, I've uploaded a new version with all the lightning talks. They have no up-to-date abstracts nor easy to obtain abstracts, and they are not published in the proceedings, so I think they shouldn't get their own page.

Perfect - thank you! I'll not make individual pages for them!

**Comment by awlassche** [comment]
Awesome! If you all feel we're ready for it, we will make some noise on the socials today that the program is online. (The small details about short and long papers can also be done after that, they only become relevant when December is coming closer.)

**Comment by MinaAlmasi** [comment]
Closing this for now - feel free to add a new issue specifying anything that you need me to add/change to the website
