### ISSUE TITLE
Accepted papers page

### ISSUE THREAD

**Issue by MinaAlmasi** [cohure/CHR2024-website#47]
Hi @marijnkoolen :)

I will remove session headings from the "Accepted Papers" page.

Should I sort the papers by short and long? Or do you prefer a long list of papers without any headings :)?

**Comment by marijnkoolen** [comment]
Yes, it would be nice to have sections with list the papers by type, e.g. Long, Short, Lightning.

**Comment by MinaAlmasi** [comment]
Cool! Ty!

**Comment by MinaAlmasi** [comment]
I have removed session headings - not sorted them as I quite like that they are chronological in some sense, but my re-evaluate later!
